!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 64
  - - buffer_size
    - 1000000
  - - gamma
    - 0.98
  - - gradient_steps
    - 1
  - - learning_rate
    - 0.1
  - - learning_starts
    - 10000
  - - n_timesteps
    - 20000
  - - noise_std
    - 0.1
  - - noise_type
    - normal
  - - policy
    - MlpPolicy
  - - policy_kwargs
    - net_arch:
      - 64
      - 64
  - - tau
    - 0.08
  - - train_freq
    - 32
