!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 64
  - - buffer_size
    - 1000000
  - - gamma
    - 0.98
  - - gradient_steps
    - 1
  - - learning_rate
    - 10
  - - learning_starts
    - 10000
  - - n_timesteps
    - 20000
  - - noise_std
    - 0.1
  - - noise_type
    - normal
  - - policy
    - MlpPolicy
  - - policy_kwargs
    - n_critics: 1
      net_arch:
      - 264
      - 264
  - - tau
    - 0.02
  - - train_freq
    - 128
