!!python/object/apply:collections.OrderedDict
- - - algo
    - ddpg
  - - conf_file
    - null
  - - device
    - auto
  - - env
    - Pendulum-v1
  - - env_kwargs
    - null
  - - eval_env_kwargs
    - null
  - - eval_episodes
    - 5
  - - eval_freq
    - 1000
  - - gym_packages
    - []
  - - hyperparams
    - batch_size: 64
      buffer_size: 1000000
      gamma: 0.98
      learning_rate: 0.0001
      policy_kwargs:
        n_critics: 1
        net_arch:
        - 264
        - 264
      tau: 0.02
      train_freq: 128
  - - log_folder
    - ddpg_train
  - - log_interval
    - -1
  - - max_total_trials
    - null
  - - n_eval_envs
    - 1
  - - n_evaluations
    - null
  - - n_jobs
    - 1
  - - n_startup_trials
    - 10
  - - n_timesteps
    - 25000
  - - n_trials
    - 500
  - - no_optim_plots
    - false
  - - num_threads
    - -1
  - - optimization_log_path
    - null
  - - optimize_hyperparameters
    - false
  - - progress
    - false
  - - pruner
    - median
  - - sampler
    - tpe
  - - save_freq
    - 50
  - - save_replay_buffer
    - false
  - - seed
    - 77239984
  - - storage
    - null
  - - study_name
    - null
  - - tensorboard_log
    - ''
  - - track
    - false
  - - trained_agent
    - ''
  - - truncate_last_trajectory
    - true
  - - uuid
    - false
  - - vec_env
    - dummy
  - - verbose
    - 1
  - - wandb_entity
    - null
  - - wandb_project_name
    - sb3
  - - wandb_tags
    - []
